server:
  port: 8082

spring:
  application:
    name: consumer

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: abhishek-group-debug-2
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JacksonJsonDeserializer
      properties:
        spring:
          json:
            trusted:
              packages: com.abhishek.kafka.model
            value:
              default:
                type: com.abhishek.kafka.model.Course